### ISSUE TITLE
griffon-trident-plugin Won't Download Jar from JCenter in Gradle 3.x Build

### ISSUE THREAD

**Issue by mecorusfc** [griffon-plugins/griffon-trident-plugin#1]
When I was trying to download this plugin using Gradle 2.11 or 2.12, both a POM and Jar downloaded.  In addition, it brought in other dependencies.  When I switched to Gradle 3.x (eventually 3.2.1), the build won't bring down the jar file and only brings down a very simple POM (different from the previous one) that has no dependencies specified in it.  I can manually specify the other dependencies and it will bring down both the POM and Jars for the other dependencies but nothing I do will cause it to bring down the Jar for this one.  The POM file now looks like this with no dependencies and apparently no jar associated:
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.codehaus.griffon.plugins</groupId>
  <artifactId>griffon-trident-plugin</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
</project>

**Comment by mecorusfc** [comment]
My attempt at pasting in the POM failed - but if you imagine the xml markup around it, it is a very simple pom with no dependencies and nothing but the project block.

**Comment by aalmiray** [comment]
Published version `1.0.1` to fix this issue.

**Comment by mecorusfc** [comment]
It didn't help.  It loaded down only the POM file for 1.0.1.  Is this a bug in Gradle 3.x?  It loaded the jar when I was using Gradle 2.1x.  It's just that the compileOnly flag messed it up for that version.

**Comment by mecorusfc** [comment]
I see now that the dependency on this page (https://bintray.com/griffon/griffon-plugins/griffon-trident-plugin#) shows it as a POM type dependency.  Maybe it was never supposed to download a jar.  I'm not sure now.  It does bring down the other dependencies correctly now (griffon-trident-swing and griffon-trident-swing-groovy).  Are these all that is needed?  If so, those jars are coming down.

**Comment by aalmiray** [comment]
Plugin POM files are designed as BOMs (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). As such they never publish JAR files.
